import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'en' | 'te' | 'hi';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'app.title': 'SkillConnect',
    'header.customer': 'Customer Dashboard',
    'header.worker': 'Worker Dashboard',
    'header.admin': 'Admin Dashboard',
    'btn.refresh': 'Refresh',
    'btn.share_location_on': '📍 Live Location On',
    'btn.share_location_off': '📍 Share Location',
    'btn.book_now': 'Book Now',
    'no_workers': 'No workers found',
    'btn.cancel': 'Cancel',
    'btn.confirm_booking': 'Confirm Booking',
  // Auth
  'auth.welcome': 'Welcome to SkillConnect',
  'auth.connect': 'Connect with skilled workers in your area',
  'auth.email_placeholder': 'Email address',
  'auth.password_placeholder': 'Password',
  'auth.sign_in': 'Sign in',
  'auth.no_account': "Don't have an account?",
  'auth.sign_up_here': 'Sign up here',
  'auth.demo_accounts': 'Demo Accounts',
  'auth.demo_customer': 'Customer Demo',
  'auth.demo_worker': 'Worker Demo',
  'auth.demo_admin': 'Admin Demo',
  'auth.demo_cred_customer': 'amit@example.com / any password',
  'auth.demo_cred_worker': 'priya@example.com / any password',
  'auth.demo_cred_admin': 'admin@labourlink.com / any password',
  'error.invalid_credentials': 'Invalid email or password',
  'error.login_failed': 'Login failed. Please try again.',
  // Register / common labels
  'register.title': 'Join SkillConnect',
  'register.subtitle': 'Create your account to get started',
  'register.i_want': 'I want to register as:',
  'role.customer': 'Customer',
  'role.worker': 'Worker',
  'role.admin': 'Admin',
  'register.find_and_book': 'Find and book skilled workers in your area',
  'register.offer_services': 'Offer your services to customers',
  'register.manage_platform': 'Manage the platform and verify bookings',
  'register.note': 'Admin accounts require special approval. Your registration will be reviewed before activation.',
  'label.full_name': 'Full Name',
  'label.username': 'Username',
  'label.password': 'Password',
  'label.confirm_password': 'Confirm Password',
  'label.email': 'Email Address',
  'label.phone': 'Phone Number',
  'label.gender': 'Gender',
  'label.district': 'District',
  'label.current_location': 'Current Location',
  'btn.get_current_location': '📍 Get Current Location',
  'select.district': 'Select District',
  'select.profession': 'Select Profession',
  'select.category': 'Select Category',
  'bio.placeholder': 'Tell us about your experience and expertise...',
  'gender.male': 'Male',
  'gender.female': 'Female',
  'gender.other': 'Other',
  'msg.select_profession_first': 'Please select a profession first to see available skills',
  'admin.registration_heading': 'Admin Registration',
  'admin.access_paragraph': 'As an admin, you will have access to:',
  'label.profession': 'Profession',
  'label.category': 'Category',
  'label.experience': 'Experience (Years)',
  'label.hourly_rate': 'Hourly Rate (₹)',
  'label.skills': 'Skills',
  'label.bio': 'Bio',
  'btn.create_account': 'Create Account',
  'auth.already_account': 'Already have an account?',
  'auth.sign_in_here': 'Sign in here',
  'error.password_mismatch': 'Passwords do not match',
  'error.password_short': 'Password must be at least 6 characters',
  'error.registration_failed': 'Registration failed. Please try again.',
  'skills.select_for': 'Select skills for {profession}',
  'error.location_unavailable': 'Unable to get your current location. Please enter manually.',
  'error.geolocation_unsupported': 'Geolocation is not supported by this browser.',
  // Dashboard / Common UI
  'header.welcome': 'Welcome',
  'btn.logout': 'Logout',
  'tab.browse': 'Browse Workers',
  'tab.bookings': 'My Bookings',
  'tab.profile': 'Profile',
  'filters.title': 'Filters',
  'filter.profession': 'Profession',
  'filter.district': 'District',
  'filter.category': 'Category',
  'filter.max_rate': 'Max Rate (₹/hr)',
  'filter.all_professions': 'All Professions',
  'filter.all_districts': 'All Districts',
  'filter.all_categories': 'All Categories',
  'filter.no_limit': 'No limit',
  'search.adjust_filters': 'Try adjusting your filters to see more results.',
  'unknown.worker': 'Unknown Worker',
  'unknown.customer': 'Unknown Customer',
  'booking.status.contact_shared': 'Contact Shared',
  'booking.no_bookings': 'No bookings yet',
  'booking.start_browsing': 'Start by browsing and booking a worker.',
  'booking.book_for': 'Book',
  'label.task': 'Task',
  'label.description': 'Description',
  'label.date': 'Date',
  'label.duration': 'Duration (hours)',
  'placeholder.example_task': 'e.g., House Cleaning',
  'placeholder.describe_work': 'Describe the work needed...',
  'contact.worker_details_title': 'Worker Contact Details',
  'contact.customer_details_title': 'Customer Contact Details',
  'contact.name': 'Name:',
  'contact.phone': 'Phone:',
  'contact.email': 'Email:',
  'contact.rate': 'Rate:',
  'contact.after_admin_verification_tip': "💡 After admin verification, you now have the worker's contact details. You can call them directly to coordinate the job.",
  'live_location.title': 'Live Location Sharing',
  'live_location.your_location': 'Your Location:',
  'live_location.worker_location': 'Worker Location:',
  'live_location.customer_location': 'Customer Location:',
  'live_location.both_visible': '🗺️ Both you and the worker can see each other\'s live location for easy coordination.',
  'btn.cancel_booking': 'Cancel Booking',
  'btn.accept': 'Accept',
  'btn.reject': 'Reject',
  'btn.mark_complete': 'Mark Complete',
  'profile.not_found': 'Worker profile not found',
  'profile.title': 'Profile Information',
  'btn.edit_profile': 'Edit Profile',
  'label.hourly_rate_short': 'Hourly Rate',
  'label.rating': 'Rating',
  'label.location': 'Location',
  'btn.save_changes': 'Save Changes',
  },
  te: {
  'app.title': 'స్కిల్ కనెక్ట్',
  'header.customer': 'వినియోగదారుల డాష్‌బోర్డ్',
  'header.worker': 'వర్కర్ డాష్‌బోర్డ్',
  'header.admin': 'అడ్మిన్ డాష్‌బోర్డ్',
  'btn.refresh': 'రిఫ్రెష్',
  'btn.share_location_on': '📍 ప్రత్యక్ష స్థానం ఆన్',
  'btn.share_location_off': '📍 స్థానం పంచుకోండి',
  'btn.book_now': 'ఇప్పుడు బుక్ చేయండి',
  'no_workers': 'వర్కర్లు కనపడలేదు',
  'btn.cancel': 'రద్దు చేయండి',
  'btn.confirm_booking': 'బుకింగ్‌ని నిర్ధారించండి',

  // Auth - Register/Login
  'auth.welcome': 'స్కిల్ కనెక్ట్‌కి స్వాగతం',
  'auth.connect': 'మీ ప్రాంతంలోని నైపుణ్య వర్కర్లతో కనెక్ట్ అవ్వండి',
  'auth.email_placeholder': 'ఈమెయిల్ చిరునామా',
  'auth.password_placeholder': 'పాస్‌వర్డ్',
  'auth.sign_in': 'సైన్ ఇన్',
  'auth.no_account': 'ఖాతా లేదా?',
  'auth.sign_up_here': 'ఇక్కడ సైన్ అప్ చేయండి',
  'auth.demo_accounts': 'డెమో ఖాతాలు',
  'auth.demo_customer': 'కస్టమర్ డెమో',
  'auth.demo_worker': 'వర్కర్ డెమో',
  'auth.demo_admin': 'అడ్మిన్ డెమో',
  'auth.demo_cred_customer': 'amit@example.com / ఏదైనా పాస్‌వర్డ్',
  'auth.demo_cred_worker': 'priya@example.com / ఏదైనా పాస్‌వర్డ్',
  'auth.demo_cred_admin': 'admin@labourlink.com / ఏదైనా పాస్‌వర్డ్',
  'error.invalid_credentials': 'చెల్లని ఈమెయిల్ లేదా పాస్‌వర్డ్',
  'error.login_failed': 'లాగిన్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',

  // Register
  'register.title': 'స్కిల్ కనెక్ట్‌లో చేరండి',
  'register.subtitle': 'ప్రారంభించడానికి మీ ఖాతాను సృష్టించండి',
  'register.i_want': 'నేను నమోదు కావాలనుకుంటున్నాను:',
  'role.customer': 'కస్టమర్',
  'role.worker': 'వర్కర్',
  'role.admin': 'అడ్మిన్',
  'register.find_and_book': 'మీ ప్రాంతంలో నైపుణ్య వర్కర్లను కనుగొని బుక్ చేయండి',
  'register.offer_services': 'మీ సేవలను కస్టమర్లకు అందించండి',
  'register.manage_platform': 'ప్లాట్‌ఫారమ్‌ను నిర్వహించి బుకింగ్‌లను ధృవీకరించండి',
  'register.note': 'అడ్మిన్ ఖాతాలకు ప్రత్యేక అనుమతి అవసరం. యాక్టివేషన్‌కి ముందు మీ నమోదు సమీక్షించబడుతుంది.',
  'label.full_name': 'పూర్తి పేరు',
  'label.username': 'యూజర్ నేమ్',
  'label.password': 'పాస్‌వర్డ్',
  'label.confirm_password': 'పాస్‌వర్డ్‌ని నిర్ధారించండి',
  'label.email': 'ఈమెయిల్ చిరునామా',
  'label.phone': 'ఫోన్ నంబర్',
  'label.gender': 'లింగం',
  'label.district': 'జిల్లా',
  'label.current_location': 'ప్రస్తుత స్థానం',
  'btn.get_current_location': '📍 ప్రస్తుత స్థానం పొందండి',
  'select.district': 'జిల్లాను ఎంచుకోండి',
  'select.profession': 'వృత్తిని ఎంచుకోండి',
  'select.category': 'వర్గాన్ని ఎంచుకోండి',
  'bio.placeholder': 'మీ అనుభవం మరియు నైపుణ్యాల గురించి వివరించండి...',
  'gender.male': 'పురుషుడు',
  'gender.female': 'మహిళ',
  'gender.other': 'ఇతరులు',
  'msg.select_profession_first': 'భాగాలను చూడటానికి ముందుగా వృత్తిని ఎంచుకోండి',
  'admin.registration_heading': 'అడ్మిన్ నమోదు',
  'admin.access_paragraph': 'అడ్మిన్‌గా, మీకు ఈ యాక్సెస్‌లు ఉంటాయి:',
  'label.profession': 'వృత్తి',
  'label.category': 'వర్గం',
  'label.experience': 'అనుభవం (సంవత్సరాలు)',
  'label.hourly_rate': 'ఘంటా రేటు (₹)',
  'label.skills': 'నైపుణ్యాలు',
  'label.bio': 'బయో',
  'btn.create_account': 'ఖాతా సృష్టించండి',
  'auth.already_account': 'ఇప్పటికే ఖాతా ఉన్నదా?',
  'auth.sign_in_here': 'ఇక్కడ సైన్ ఇన్ చేయండి',
  'error.password_mismatch': 'పాస్‌వర్డ్లు సరిపోలడం లేదు',
  'error.password_short': 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి',
  'error.registration_failed': 'నమోదు విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
  'skills.select_for': '{profession} కోసం నైపుణ్యాలను ఎంచుకోండి',
  'error.location_unavailable': 'మీ ప్రస్తుత స్థానం పొందలేకపోయాం. దయచేసి మాన్యువల్‌గా నమోదు చేయండి.',
  'error.geolocation_unsupported': 'ఈ బ్రౌజర్ జియోలొకేషన్‌కి మద్దతు ఇవ్వదు.',
},
  hi: {
  'app.title': 'स्किल कनेक्ट',
  'header.customer': 'कस्टमर डैशबोर्ड',
  'header.worker': 'वर्कर डैशबोर्ड',
  'header.admin': 'ऐडमिन डैशबोर्ड',
  'btn.refresh': 'रिफ्रेश',
  'btn.share_location_on': '📍 लाइव लोकेशन ऑन',
  'btn.share_location_off': '📍 लोकेशन साझा करें',
  'btn.book_now': 'अभी बुक करें',
  'no_workers': 'कोई वर्कर नहीं मिला',
  'btn.cancel': 'रद्द करें',
  'btn.confirm_booking': 'बुकिंग की पुष्टि करें',

  // Auth - Register/Login
  'auth.welcome': 'स्किल कनेक्ट में आपका स्वागत है',
  'auth.connect': 'अपने क्षेत्र के कुशल वर्करों से जुड़ें',
  'auth.email_placeholder': 'ईमेल पता',
  'auth.password_placeholder': 'पासवर्ड',
  'auth.sign_in': 'साइन इन',
  'auth.no_account': 'क्या आपका खाता नहीं है?',
  'auth.sign_up_here': 'यहाँ साइन अप करें',
  'auth.demo_accounts': 'डेमो अकाउंट्स',
  'auth.demo_customer': 'कस्टमर डेमो',
  'auth.demo_worker': 'वर्कर डेमो',
  'auth.demo_admin': 'ऐडमिन डेमो',
  'auth.demo_cred_customer': 'amit@example.com / कोई भी पासवर्ड',
  'auth.demo_cred_worker': 'priya@example.com / कोई भी पासवर्ड',
  'auth.demo_cred_admin': 'admin@labourlink.com / कोई भी पासवर्ड',
  'error.invalid_credentials': 'अमान्य ईमेल या पासवर्ड',
  'error.login_failed': 'लॉगिन विफल हुआ। कृपया दोबारा प्रयास करें।',

  // Register
  'register.title': 'स्किल कनेक्ट से जुड़ें',
  'register.subtitle': 'शुरू करने के लिए अपना खाता बनाएं',
  'register.i_want': 'मैं पंजीकरण करना चाहता हूँ:',
  'role.customer': 'कस्टमर',
  'role.worker': 'वर्कर',
  'role.admin': 'ऐडमिन',
  'register.find_and_book': 'अपने क्षेत्र के कुशल वर्करों को खोजें और बुक करें',
  'register.offer_services': 'अपनी सेवाएँ कस्टमर्स को प्रदान करें',
  'register.manage_platform': 'प्लेटफ़ॉर्म प्रबंधित करें और बुकिंग सत्यापित करें',
  'register.note': 'ऐडमिन अकाउंट्स के लिए विशेष अनुमोदन आवश्यक है। सक्रियण से पहले आपका पंजीकरण समीक्षा किया जाएगा।',
  'label.full_name': 'पूरा नाम',
  'label.username': 'यूज़रनेम',
  'label.password': 'पासवर्ड',
  'label.confirm_password': 'पासवर्ड की पुष्टि करें',
  'label.email': 'ईमेल पता',
  'label.phone': 'फ़ोन नंबर',
  'label.gender': 'लिंग',
  'label.district': 'जिला',
  'label.current_location': 'वर्तमान स्थान',
  'btn.get_current_location': '📍 वर्तमान स्थान प्राप्त करें',
  'select.district': 'जिला चुनें',
  'select.profession': 'पेशे का चयन करें',
  'select.category': 'श्रेणी चुनें',
  'bio.placeholder': 'अपने अनुभव और कौशल के बारे में बताएं...',
  'gender.male': 'पुरुष',
  'gender.female': 'महिला',
  'gender.other': 'अन्य',
  'msg.select_profession_first': 'उपलब्ध कौशल देखने के लिए कृपया पहले पेशा चुनें',
  'admin.registration_heading': 'ऐडमिन पंजीकरण',
  'admin.access_paragraph': 'एक ऐडमिन के रूप में, आपके पास इन तक पहुंच होगी:',
  'label.profession': 'पेशा',
  'label.category': 'श्रेणी',
  'label.experience': 'अनुभव (वर्ष)',
  'label.hourly_rate': 'प्रति घंटा दर (₹)',
  'label.skills': 'कौशल',
  'label.bio': 'बायो',
  'btn.create_account': 'खाता बनाएं',
  'auth.already_account': 'क्या आपके पास पहले से एक खाता है?',
  'auth.sign_in_here': 'यहाँ साइन इन करें',
  'error.password_mismatch': 'पासवर्ड मेल नहीं खाते',
  'error.password_short': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
  'error.registration_failed': 'पंजीकरण विफल हुआ। कृपया पुनः प्रयास करें।',
  'skills.select_for': '{profession} के लिए कौशल चुनें',
  'error.location_unavailable': 'आपका वर्तमान स्थान प्राप्त नहीं किया जा सका। कृपया मैन्युअल रूप से दर्ज करें।',
  'error.geolocation_unsupported': 'यह ब्राउज़र जियोलोकेशन का समर्थन नहीं करता है।',
},
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>('en');

  const t = (key: string) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

export default LanguageContext;
